// The real module is generated by `npm run build:wasm`. This declaration lets
// Svelte type-check source before that generated package exists.
declare function init(): Promise<unknown>
declare function parse_bam_header_json(bytes: Uint8Array): unknown
declare function query_bam_reference_json(bytes: Uint8Array, referenceIndex: number): unknown
declare function query_bam_region_json(bytes: Uint8Array, referenceIndex: number, start: number, end: number): unknown
declare function query_bam_region_filtered_json(bytes: Uint8Array, referenceIndex: number, start: number, end: number, filter: unknown): unknown
declare function parse_fasta_references_json(bytes: Uint8Array): unknown
declare function parse_fai_references_json(bytes: Uint8Array): unknown
declare class FastaFile {
  constructor(bytes: Uint8Array)
  references_json(): unknown
  reference_slice_json(name: string, start: number, end: number): unknown
  free(): void
}

export { FastaFile, parse_bam_header_json, query_bam_reference_json, query_bam_region_json, query_bam_region_filtered_json, parse_fasta_references_json, parse_fai_references_json }
export default init
