// The real module is generated by `npm run build:wasm`. This declaration lets
// Svelte type-check source before that generated package exists.
declare function init(): Promise<unknown>
declare function parse_bam_header_json(bytes: Uint8Array): unknown
declare function query_bam_reference_json(bytes: Uint8Array, referenceIndex: number): unknown

export { parse_bam_header_json, query_bam_reference_json }
export default init
